<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>a51</string>
	</array>
	<key>name</key>
	<string>8051 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(dword|qword|tword|db|dw|dd|dq|dt|do|dy|ds|dbit|resb|resw|resd|resq|rest|reso|resy|incbin|equ|times)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(data|bss|text)$</string>
			<key>name</key>
			<string>string.section</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>["']</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.asm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>["']</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.asm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.asm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.c</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*[#%]\s*(error|warning)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.error.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.preprocessor.diagnostic.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*[#%]\s*(include|import)\b\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.c.include</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.c</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.c</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.include.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.c</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.c</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.lt-gt.include.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*[%#]\s*(define|defined|elif|else|if|ifdef|ifndef|line|pragma|undef|endif)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(r[0-7])\b</string>
			<key>name</key>
			<string>variable.parameter.regular</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(p[0-3]|[pt]con|tmod|t[lh][01]|dp([lh]|tr)|scon|sbuf|i[ep]|sp|psw|a(cc)?|b|c|ar[0-7])\b</string>
			<key>name</key>
			<string>variable.parameter.special</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(addc?|subb|inc|dec|mul|div|da|clr|cpl|r[lr]c?|swap)\b</string>
			<key>name</key>
			<string>keyword.operator.mnemonic.math</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b((an|or|xr)l)\b</string>
			<key>name</key>
			<string>keyword.operator.mnemonic.logic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(clr|setb|cpl|anl|orl|mov)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.bool</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b([al]call|reti?|[als]?jmp|j(n?z|n?c|n?b|bc)|cjne|djnz|nop)\b</string>
			<key>name</key>
			<string>keyword.control.mnemonic.flow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(mov[cx]?|push|pop|xchd?)\b</string>
			<key>name</key>
			<string>keyword.other.mnemonic.data</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\.?\w+:\s*(?=$|;)</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[0-9a-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.literal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9a-fA-F]+[hH])\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([01]+[bB])\b</string>
			<key>name</key>
			<string>constant.numeric.bin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@\w+(\+\w+)?</string>
			<key>name</key>
			<string>storage.modifier.indirect</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#\w+(\+\w+)?</string>
			<key>name</key>
			<string>storage.modifier.immediate</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.?(globl|global)\b</string>
			<key>name</key>
			<string>entity.directive</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.8051</string>
	<key>uuid</key>
	<string>e8946f0f-a287-4340-943d-fc3954651928</string>
</dict>
</plist>
